---
name: module3_task2

"on":  # do something on push to main
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''
      - run: |
          cd module3_task2/ && ./setup.sh && make build
